#!/bin/bash
function invalid() {
    echo -e Invalid usage
    echo -e Try \'xfce4-theme-switcher --help\' for more information
    exit
}
function help() {
    echo -e "\nUsage:"
    echo -e " xfce4-theme-switcher [OPTION]"
    echo -e " xfce4-theme-switcher -l [THEME NAME]"
    echo -e " xfce4-theme-switcher -s [THEME NAME]"
    echo -e " xfce4-theme-switcher -d [THEME NAME]\n"
    echo -e "Change or save different thmemes for the xfce4 desktop environment.\n"
    echo -e "Options:"
    echo -e " -d\t\tdelete a theme given by the theme name"
    echo -e " -l\t\tload a theme given by the theme name"
    echo -e " -n\t\tcycle to the next theme"
    echo -e " -p\t\tcycle to the previous theme"
    echo -e " -s\t\tsave the current xfce4 settings as a theme given the theme name"
    echo -e " --list\t\tlist all themes"
    echo -e " --help\t\tdisplay this help"
    echo -e " --dmenu\tsaves (wal generated) dmenu colors"
    echo -e " --wal-theme\tsaves pywal terminal color-scheme"
    echo -e "\t\tmust have pywal to use"
    echo -e "\t\tonly use on saves\n"
    exit
}

function load_theme() {
    array=("xsettings" "xfwm4" "xfce4-desktop" "xfce4-panel")
    for file in ${array[@]}
    do
        echo $config_loc/$file.conf | xargs cat | while read -r line
        do
            count=0
            property=""
            value=""
            for word in $line
            do
                if [ $count -gt "0" ];
                then
                    value="$value $word"
                else
                    property="$property $word"
                fi
                let "count++"
            done
            property="$(echo -e "${property}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            value="$(echo -e "${value}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            rm $config_loc/*log &> /dev/null
            xfconf-query -c $file -p $property -s "$value" &>> $config_loc/$log_name.log
            if [ $? -eq "0" ];
            then
                echo -e Changed $property to the value $value &>> $config_loc/$log_name.log
            else
                echo -e ERROR: Could not change $property to the value $value &>> $config_loc/$log_name.log
            fi
        done
    done
    cp /$config_loc/terminalrc /home/$USER/.config/xfce4/terminal/terminalrc &>> $config_loc/$log_name.log
    echo -e Loaded terminal preferences &>> $config_loc/$log_name.log
    if [ -f $config_loc/sequences ]; then
        cp $config_loc/sequences /home/$USER/.cache/wal/sequences
        ls -1 /dev/pts | while read -r terminal;
        do
            if [ $terminal != "ptmx" ];
            then
                (cat ~/.cache/wal/sequences &) > /dev/pts/$terminal
            fi
        done
    else
        #TODO
        #going from wal-theme terminal to normal terminal
        rm $HOME/.cache/wal/sequences
        ls -1 /dev/pts | while read -r terminal;
        do
            if [ $terminal != "ptmx" ];
            then
                tset > /dev/pts/$terminal #DOES NOT WORK 
            fi
        done
    fi
    if [ -f $config_loc/colors.sh ]; then
        cp $config_loc/colors.sh /home/$USER/.cache/wal/colors.sh &> /dev/null
    fi
    xfce4-panel -r
    echo $theme_load > /home/$USER/.config/xfce4-theme-switcher/theme.current
    lightdm
}

#TODO#
#need to check for permission to lightdm config file. If no permission, prompt to change permission??
#also maybe change wallpaper and font too
function lightdm() {
    #replace theme
    wm_theme="$(xfconf-query -c xfwm4 -p /general/theme)" #get loaded theme
    sed -Ei "s/theme-name.*/theme-name = $wm_theme/" /etc/lightdm/lightdm-gtk-greeter.conf #replace theme in config file
    #replace font
    wm_font="$(xfconf-query -c xfwm4 -p /general/title_font)" #get loaded font
    sed -Ei "s/font-name.*/font-name= $wm_font/" /etc/lightdm/lightdm-gtk-greeter.conf
}

###########################################
############ start of script ##############
###########################################
wal_enabled=false
dmenu_enabled=false
if [ $# -eq 0 ];
then
    invalid
fi

if [ ! -d /home/$USER/.config/xfce4-theme-switcher ];
then
    mkdir /home/$USER/.config/xfce4-theme-switcher
fi

config_loc="/home/$USER/.config/xfce4-theme-switcher/$2"
log_name=$(date +"%m%d%y_%H%M%S")

if [ $1 = "-l" ]; #change the theme to the name given
then
    theme_load=$2
    load_theme
elif [ $1 = "-n" ] || [ $1 = "-p" ];
then
    theme_current=$(cat /home/$USER/.config/xfce4-theme-switcher/theme.current)
    theme_array=()
    for i in $( ls /home/$USER/.config/xfce4-theme-switcher);
    do
        if [ -d /home/$USER/.config/xfce4-theme-switcher/$i ];
        then
            theme_array+=($i)
        fi
    done
    count=0
    found=false
    for theme in ${theme_array[@]};
    do
        if [ "$theme" = "$theme_current" ];
        then
            break #found theme
        fi
        ((count++))
    done
    size=$((${#theme_array[@]}-1))
    if [ $1 = "-n" ];
    then
        if [ $count -eq $size ];
        then
            theme_load=${theme_array[0]}
        else
            ((count++))
            theme_load=${theme_array[$count]}
        fi
        config_loc="/home/$USER/.config/xfce4-theme-switcher/$theme_load"
        load_theme
        exit
    else
        if [ $count -eq 0 ];
        then
            theme_load=${theme_array[$size]}
        else
            ((count--))
            theme_load=${theme_array[$count]}
        fi
        config_loc="/home/$USER/.config/xfce4-theme-switcher/$theme_load"
        load_theme
        exit
    fi
elif [ $1 = "-s" ]; #save a new theme using current settings
then
    for i in $@
    do
        if [ $i = "--wal-theme" ];
        then
            wal_enabled=true
        fi
        if [ $i = "--dmenu" ]; then
            dmenu_enabled=true
        fi
    done
    if [ -d $config_loc ];
    then
        echo Theme $2 already exists! Do you want to overwrite it? [y/n]
        read input
        if [ $input != "y" ];
        then
            exit
        fi
    else
        mkdir $config_loc
    fi
    xfconf-query -c xsettings -lv > $config_loc/xsettings.conf
    echo -e Generated xsettings theme $2
    xfconf-query -c xfwm4 -lv > $config_loc/xfwm4.conf
    echo -e Generated xfwm4 theme $2
    xfconf-query -c xfce4-desktop -lv > $config_loc/xfce4-desktop.conf
    echo -e Generated desktop theme $2
    xfconf-query -c xfce4-panel -lv > $config_loc/xfce4-panel.conf
    echo -e Generated panel theme $2
    cp /home/$USER/.config/xfce4/terminal/terminalrc $config_loc/terminalrc &> /dev/null
    echo -e Copied terminal preferences
    if [ "$wal_enabled" = true ]; then
        cp /home/$USER/.cache/wal/sequences $config_loc/sequences &> /dev/null
        echo wal theme saved
    fi
    if [ "$dmenu_enabled" = true ]; then
        cp /home/$USER/.cache/wal/colors.sh $config_loc/colors.sh &>/dev/null
        echo dmenu theme saved
    fi
    echo $2 > /home/$USER/.config/xfce4-theme-switcher/theme.current
elif [ $1 = "-d" ]; #delete theme
then
    echo Are you sure you want to delete xfce4 theme $2? [y/n]
    read input
    if [ $input != "y" ];
    then
        exit
    fi
    rm -rf $config_loc
elif [ $1 = "--list" ]; #list all themes
then
    for theme in $(ls /home/$USER/.config/xfce4-theme-switcher);
    do
        if [ -d /home/$USER/.config/xfce4-theme-switcher/$theme ];
        then
            echo $theme
        fi
    done
elif [ $1 == "--help" ];
then
    help
else
    invalid
fi
